API_HEADERS=[
    "id",
    "type",
    "sectionId",
    "sectionName",
    "webPublicationDate",
    "webTitle",
    "webUrl",
    "apiUrl",
    "isHosted",
    "pillarId",
    "pillarName",
    "wordcount"
]

SENTIMENTS=[
    "negative",
    "neutral",
    "positive",
    "compound"
]

REPORT_HEADERS=[
    "id",
    "type",
    "sectionId",
    "sectionName",
    "webPublicationDate",
    "formattedDate",
    "year"
    "webTitle",
    "webUrl",
    "apiUrl",
    "isHosted",
    "pillarId",
    "pillarName",
    "wordcount",
    "negative",
    "neutral",
    "positive",
    "compound"
]

API_KEY="44c54c3b-1bb5-4b01-9f06-7ea0496ca617"